name: Notify DingTalk on GitHub Push

on:
  push:  # 监听所有分支的 push 事件

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate DingTalk Signature and Send notification
        run: |
          COMMIT_AUTHOR=$(git log -1 --format='%an')
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA | tr '\n' ',' | sed 's/,$//')

          echo ${COMMIT_AUTHOR}
          echo ${COMMIT_SHA}
          echo ${COMMIT_FILES}

          curl -X POST https://oapi.dingtalk.com/robot/send?access_token=bada4bbd50de162fe754b3f7519768a4ae30558c2a1464a7cbf6c28b3857799f \
          -H "Content-Type: application/json" \
          -d '{
            "msgtype": "markdown",
            "markdown": {
              "title": "GitHub Push Notification",
              "text": "## GitHub 仓库更新\n\n**Author**: '"${COMMIT_AUTHOR}"'\n**Commit SHA:** '"${COMMIT_SHA}"'
            }
          }'
