name: Notify DingTalk on GitHub Push

on:
  push:  # 监听所有分支的 push 事件

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Generate DingTalk Signature and Send notification
      run: |
        timestamp=$(($(date +%s%N)/1000000))
        timestamp="1725441011274"
        echo "Timestamp: $timestamp"

        secret="SEC29db82f7d6562f71f4e6ea51757cbdb0b75d982d17df2583fa4bdfed58fcac6b"
        secret_enc=$(echo -n "$secret" | iconv -t utf-8)

        string_to_sign="$timestamp\n$secret"
        string_to_sign_enc=$(echo -n "$string_to_sign" | iconv -t utf-8)

        hmac_code=$(echo -n "$string_to_sign_enc" | openssl dgst -sha256 -hmac "$secret_enc" -binary)

        base64_encoded=$(echo "$hmac_code" | openssl base64 -A)

        sign=$(echo -n "$base64_encoded" | jq -sRr @uri)
        echo "Sign: $sign"

        curl -X POST "https://oapi.dingtalk.com/robot/send?access_token=bada4bbd50de162fe754b3f7519768a4ae30558c2a1464a7cbf6c28b3857799f&timestamp=${timestamp}&sign=${sign}" \
        -H "Content-Type: application/json" \
        -d '{
          "msgtype": "markdown",
          "markdown": {
            "title": "GitHub Push Notification",
            "text": "## GitHub 仓库更新\n\n**仓库**: ${GITHUB_REPOSITORY}\n**分支**: ${GITHUB_REF}\n**提交**: ${GITHUB_SHA}\n**触发者**: ${GITHUB_ACTOR}\n"
          }
        }'
