name: Notify DingTalk on GitHub Push

on:
  push:  # 监听所有分支的 push 事件

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate DingTalk Signature and Send notification
        run: |
          curl -X POST https://oapi.dingtalk.com/robot/send?access_token=bada4bbd50de162fe754b3f7519768a4ae30558c2a1464a7cbf6c28b3857799f \
          -H "Content-Type: application/json" \
          -d '{
            "msgtype": "markdown",
            "markdown": {
              "title": "GitHub Push Notification",
              "text": "## GitHub 仓库更新\n\n"
            }
          }'
