name: Notify DingTalk on GitHub Push

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate DingTalk Signature
      id: generate-sign
      run: |
        python3 -c "
import hmac
import hashlib
import base64
import urllib.parse
import time

# 获取当前时间戳
timestamp = str(round(time.time() * 1000))
secret = 'SEC29db82f7d6562f71f4e6ea51757cbdb0b75d982d17df2583fa4bdfed58fcac6b'

# 生成签名字符串
string_to_sign = '{}\n{}'.format(timestamp, secret)

# 计算 HMAC-SHA256 签名并进行 Base64 编码
hmac_code = hmac.new(secret.encode('utf-8'), string_to_sign.encode('utf-8'), digestmod=hashlib.sha256).digest()
sign = urllib.parse.quote_plus(base64.b64encode(hmac_code).decode('utf-8'))

# 输出时间戳和签名
print(f'::set-output name=timestamp::{timestamp}')
print(f'::set-output name=sign::{sign}')
"

    - name: Send Notification to DingTalk
      run: |
        curl -X POST "https://oapi.dingtalk.com/robot/send?access_token=YOUR_ACCESS_TOKEN&timestamp=${{ steps.generate-sign.outputs.timestamp }}&sign=${{ steps.generate-sign.outputs.sign }}" \
        -H "Content-Type: application/json" \
        -d '{
          "msgtype": "markdown",
          "markdown": {
            "title": "GitHub Push Notification",
            "text": "## GitHub 仓库更新\n\n**仓库**: ${GITHUB_REPOSITORY}\n**分支**: ${GITHUB_REF}\n**提交**: ${GITHUB_SHA}\n**触发者**: ${GITHUB_ACTOR}\n"
          }
        }'
