name: Notify DingTalk on GitHub Push

on:
  push:  # 监听所有分支的 push 事件

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保克隆完整的提交历史

      - name: Set Environment to UTF-8
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8

      - name: Send Notification to DingTalk
        run: |
          COMMITTER_DATE=$(git log -1 --pretty=%cI)
          echo "COMMITTER_DATE: $COMMITTER_DATE"

          COMMIT_AUTHOR=$(git log -1 --format='%an')
          echo "COMMIT_AUTHOR: $COMMIT_AUTHOR"

          COMMIT_SHA=$(git rev-parse HEAD)
          echo "COMMIT_SHA: $COMMIT_SHA"

          FILES_MODIFIED=$(git diff-tree --no-commit-id --diff-filter=M --name-only -r $COMMIT_SHA)
          FILES_MODIFIED=$(printf "$FILES_MODIFIED")
          FILES_MODIFIED=$(echo "$FILES_MODIFIED" | sed 's/"//g')
          echo "FILES_MODIFIED: $FILES_MODIFIED"

          FILES_ADDED=$(git diff-tree --no-commit-id --diff-filter=A --name-only -r $COMMIT_SHA)
          FILES_ADDED=$(printf "$FILES_ADDED")
          FILES_ADDED=$(echo "$FILES_ADDED" | sed 's/"//g')
          echo "FILES_ADDED: $FILES_ADDED"

          MESSAGE="## [GitHub 仓库更新](https://github.com/hzm1124/YangTeng)\n\n- - -\n\n- ***Time***: ${COMMITTER_DATE}\n\n- ***Author***: ${COMMIT_AUTHOR}\n\n- ***Commit SHA***: ${COMMIT_SHA}\n\n- - -\n\n- ***Files Modified***:\n\`\`\`\n${FILES_MODIFIED}\n\`\`\`\n\n- - - \n\n- ***Files Added***:\n\`\`\`\n${FILES_ADDED}\n\`\`\`"

          curl -X POST https://oapi.dingtalk.com/robot/send?access_token=79d97a0de5f5c45b2a35e41cf192643dc6e8c9068bc1f9d48d67a5d1011c9b9bfuck \
          -H "Content-Type: application/json" \
          -d '{"msgtype": "markdown", "markdown": {"title": "GitHub Push Notification", "text": "'"${MESSAGE}"'"}}'
