name: Notify DingTalk on GitHub Push

on:
  push:  # 监听所有分支的 push 事件

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保克隆完整的提交历史

      - name: Send Notification to DingTalk
        run: |
          COMMITTER_DATE=$(git log -1 --pretty=%cI)
          echo "COMMITTER_DATE: $COMMITTER_DATE"

          COMMIT_AUTHOR=$(git log -1 --format='%an')
          echo "COMMIT_AUTHOR: $COMMIT_AUTHOR"

          COMMIT_SHA=$(git rev-parse HEAD)
          echo "COMMIT_SHA: $COMMIT_SHA"

          COMMIT_FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA)
          echo "COMMIT_FILES: $COMMIT_FILES"

          MESSAGE="# [GitHub 仓库更新](https://github.com/hzm1124/YangTeng)\n- - -<br />***Time:*** ${COMMITTER_DATE}\n\n<br />**Author:** ${COMMIT_AUTHOR}\n\n**Commit SHA:** ${COMMIT_SHA}\n\n**Files Changed:**\n\`\`\`\n${COMMIT_FILES}\n\`\`\`"

          curl -X POST https://oapi.dingtalk.com/robot/send?access_token=bada4bbd50de162fe754b3f7519768a4ae30558c2a1464a7cbf6c28b3857799f \
          -H "Content-Type: application/json" \
          -d '{"msgtype": "markdown", "markdown": {"title": "GitHub Push Notification", "text": "'"${MESSAGE}"'"}}'
